In [1]:
import numpy as np
import torch

# 1. 파이토치 패키지의 기본 구성


## torch
메인 네임스페이스. 텐서 등의 다양한 수학 함수 들어가 있음.numpy와 비슷한 구조


## torch.autograd
자동 미분을 위한 함수들이 내포. 자동미분을 모듈처럼 제어 가능하며, context manager(enable_grad/nograd)나 자체 미분 가능 함수를 정의할 때 사용하는 기반 클래스인 function 등이 이에 포함됨

## torch.nn
신경망을 구축하ㅏ기 위한 다양한 데이터 구조 및 레이어 등의 정의되어 있음.
RNN, LSTM과 같은 layer나 ReLU 같은 activation function, MSELoss와 같은 loss function들이 들어있음

## torch.optim
Stochastic Gradient Descent(SGD)를 중심으로 한 파라미터 optimization 알고리즘이 구현되어 있음

## torch.utils.data
SGD의 반복 연산을 실행할 때 사용하는 mini batch 용 utility function이 여기에 포함됨

## torch.onnx
ONNX(: Open Neural Network Exchange)의 포맷으로 모델을 export 할 때 사용. ONNX는 서로 다른 딥 러닝 프레임워크 간에 모델을 공유할 때 사용하는 포맷

#2. Tensor Manipulation

해당 셀에서는 vector, martix, tensor에 대해 이해하고, Numpy와 파이토치로 이들을 다루는 방법에 대해 이해한다


## preview
>  **vector, matrix and tensor** : DL을 위한 기본적인 수학 지식인 vector, martix, tensor에 대해 알아본다

> **Numpy Review** : pytorch는 python 패키지 Numpy와 유사하다. pytorch의 근간이 되는 Numpy에 대해 살펴본다.

> **Pytorch Tensor Allocation** : Numpy 실습 후 pytorch의 tensor 선언 방법에 대해 알아본다.

> **Matrix Manipulation** : 행렬 연산에 대해 이해한다

> **Other Basic Ops** : 다른 기본적인 오퍼레이션들에 대해 이해한다

## Vector, Matrix and Tensor

## PyTorch Tensor Shape Convention

**Vector** : 1차원의 Tensor. 보통 Vector라 부르긴 하지만, Tensor안에 포함되는 개념.

**Matrix** : 2차원의 Tensor. batch_size * Dimension 로 표현하기도 한다.

**3D Tensor(in Typical Computer Vision)**
: 비전 분야에서 사용되는 3차원 tensor로, width * batch_size * height로 구성된다.

**3D Tensor(in Typical Natural Language Procsessing)** : NLP 분야에서의 3차원 tensor로, length * batch_size * dim 으로 구성.(batchsize, 문장 길이, 단어 벡터의 차원)


### 백문이 불여일견. 코드로 살펴보자.

#### 1D with Numpy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함.
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


##### Numpy 기초 이해하기

In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # 인덱스를 통한 원소 접근

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [5]:
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1]) # [시작 번호 : 끝 번호]로 범위 지정을 통해 가져온다.

t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]


In [6]:
print('t[:2] t[3:]     = ', t[:2], t[3:]) # 시작 번호를 생략한 경우와 끝 번호를 생략한 경우

t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


#### 2D with Numpy

In [7]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


#### PyTorch Tensor Allocation

#####1D with PyTorch

In [9]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [10]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [11]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


#####2D with PyTorch

In [12]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [13]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [14]:
print(t[:, 1]) # 모든 첫번째 차원의 두번째 정보를 가져옴(모든 첫 차원에 대해, 두 번째 차원의 두번째 정보를 가져옴)
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [15]:
print(t[:, :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


##### 브로드캐스팅(Broadcasting)

In [16]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


위의 경우엔 m1,과 m2의 크기는 둘 다 (1, 2)이다. 아래의 경우에는 m1의 크기는 (1, 2)이며 m2의 크기는 (1,) 이게 되는데, 해당 과정에서 broadcasting을 통해 이를 연산한다

In [17]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [18]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


위의 경우에는 m1의 크기는 (1, 2), m2의 크기는 (2, 1)이다. 이 경우에도 broadcasting이 작용. (2,2)로 크기를 변경하여 덧셈을 수행.
아래와 같이 작용된다.

[1, 2]
==> [[1, 2],
     [1, 2]]

     
[3]
[4]
==> [[3, 3],
     [4, 4]]


##### 자주 사용되는 기능들


###### 행렬 곱셈과 곱셈의 차이(Matrix Multiplication Vs. Multiplication)

행렬로 곱셈을 하는 방법은 크게 두 가지가 있다. 행렬 곱셈(.matmul)과 원소 별 곱셈(.mul)이 있다.

In [19]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


위는 2 x 2 행렬과 2 x 1 행렬(벡터)의 행렬 곱셈의 결과를 보여준다.

여기에, element-wise 곱셈이라는 것이 존재한다. 동일한 크기의 행렬이 동일한 위치에 있는 우너소끼리 곱하는 것을 말하는데, 이는 * 또는 mul()을 통해 수행한다.

In [20]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


위에서 m1 행렬의 크기는 (2, 2)이고, m2 행렬의 크기는 (2, 1)이다. 이때 element-wise 곱셈을 수행하면, 두 행렬의 크기는 브로드캐스팅이 된 후에 곱셈을 수행하게 된다. 여기서는 m2의 크기가 다음과 같이 변환된다.

[1]
[2]
==> [[1, 1],
     [2, 2]]

###### 평균(Mean)

In [21]:
t = torch.FloatTensor([1, 2])
print(t.mean())


tensor(1.5000)


In [22]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [23]:
print(t.mean())

tensor(2.5000)


위에서 4개의 원소의 평균인 2.5가 나오는걸 확인할 수 있다.
아래서는 차원(dimension)을 인자로 주는 경우를 다룬다.

In [24]:
print(t.mean(dim=0))


tensor([2., 3.])


dim=0은 첫번째 차원, 즉 '행'을 의미한다. 인자로 dim을 주면 **해당 차원을 제거**한다는 의미이므로, 행을 제거하고 열만 남기게 된다. 기존 (2, 2) 크기에서 열의 차원만 보존되어 (2,) 크기가 된다.
```
t.mean(dim=0) : 입력에서 첫번째 차원(행)을 제거
[[1., 2.],
 [3., 4.]]
1과 3의 평균, 2와 4의 평균을 구한다.
결과 ==> [2., 3.]
```

In [25]:
print(t.mean(dim=1)) # 두번째 차원(열)을 제거

tensor([1.5000, 3.5000])


dim=1은 두번째 차원(열)을 제거한다. 따라서 각 행의 평균이 구해진다. 1과 2의 평균, 3과 4의 평균이므로 결과는 [1.5, 3.5]가 된다.

In [26]:
print(t.mean(dim=-1)) # 마지막 차원을 제거 → 여기서는 열 제거와 동일

tensor([1.5000, 3.5000])


dim=-1은 마지막 차원을 제거하라는 의미이고, 현재 텐서에서는 결국 열을 제거하는 것과 같다. 그러므로 dim=1을 준 경우와 출력 결과가 동일하다.

###### 덧셈(Sum)

덧셈(Sum)은 평균(Mean)과 연산 방법이나 인자가 의미하는 바가 정확히 동일하다. 다만 평균이 아니라 합을 구할 뿐이다.

In [27]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
print(t.sum())       # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0))  # 행을 제거
print(t.sum(dim=1))  # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


###### 최대(Max)와 아그맥스(ArgMax)

최대(Max)는 원소의 최대값을 리턴하고, 아그맥스(ArgMax)는 그 최대값을 가진 인덱스를 리턴한다.

In [29]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [30]:
print(t.max()) # Returns one value: max

tensor(4.)


원소 중 최대값인 4를 리턴한다. 이번엔 인자로 dim=0을 주어 첫번째 차원(행)을 제거해본다.

In [31]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


행의 차원을 제거하므로 (2,) 텐서가 만들어지고 max 결과는 [3., 4.]이다. 그런데 [1, 1]이라는 값도 함께 리턴되는데, 이는 max에 dim 인자를 주면 argmax(최대값의 인덱스)도 함께 리턴하기 때문이다.
```
[[1, 2],
 [3, 4]]
첫번째 열에서 0번 인덱스는 1, 1번 인덱스는 3 → 최대값 3의 인덱스는 1
두번째 열에서 0번 인덱스는 2, 1번 인덱스는 4 → 최대값 4의 인덱스는 1
따라서 argmax는 [1, 1]
```
max 또는 argmax만 따로 받고 싶다면 리턴값에 인덱스를 부여하면 된다. [0]은 max, [1]은 argmax를 가져온다.

In [32]:
print('Max: ', t.max(dim=0)[0])    # max 값만
print('Argmax: ', t.max(dim=0)[1]) # argmax 값만

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [33]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


###### 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경 (매우 중요!)

파이토치의 뷰(View)는 넘파이의 리쉐이프(Reshape)와 같은 역할로, 텐서의 크기(shape)를 변경한다. 단, **변경 전후 원소의 개수는 반드시 유지**되어야 한다. 실습을 위해 우선 (2, 2, 3) 크기의 3차원 텐서를 만든다.

In [34]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


현재 텐서의 크기는 (2, 2, 3)이다. 이 텐서를 가지고 두 번의 실습을 진행한다.

**(1) 3차원 텐서 → 2차원 텐서로 변경**

view를 사용해 ft 텐서의 크기를 2차원으로 변경해본다.

In [35]:
print(ft.view([-1, 3]))       # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


view([-1, 3])에서 **-1은 '첫번째 차원의 크기는 파이토치가 알아서 정하라'**는 의미이고, **3은 두번째 차원의 길이를 3으로 하라**는 의미다. 즉 (?, 3) 크기로 바꾸라는 뜻이고, 결과적으로 (4, 3)의 텐서를 얻는다.

내부적으로는 (2, 2, 3) → (2 × 2, 3) → (4, 3) 으로 변환된다.

규칙을 정리하면,
- view는 변경 전과 변경 후의 원소 개수가 유지되어야 한다.
- 크기에 -1이 들어가면 다른 차원으로부터 그 값을 유추한다.

변경 전 원소 수는 (2 × 2 × 3) = 12개, 변경 후 원소 수도 (4 × 3) = 12개로 동일하다.

**(2) 3차원 텐서의 크기 변경 (차원은 유지)**

이번엔 차원은 3차원으로 유지하되 크기(shape)만 바꿔본다. 원소 수는 유지되어야 하므로 (2 × 2 × 3) = (? × 1 × 3) = 12를 만족하려면 ?는 4가 된다.

In [36]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


###### 스퀴즈(Squeeze) - 1인 차원을 제거

스퀴즈는 차원이 1인 경우 해당 차원을 제거한다. 실습을 위해 (3, 1) 크기의 2차원 텐서를 만든다.

In [37]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


해당 텐서는 (3, 1) 크기를 가진다. 두번째 차원이 1이므로 squeeze를 사용하면 그 차원이 제거되어 (3,) 크기의 1차원 벡터가 된다.

In [38]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


###### 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가

언스퀴즈는 스퀴즈와 정반대로, 특정 위치에 1인 차원을 추가한다. (어느 위치에 추가할지 인자로 명시해야 한다.) 실습을 위해 (3,) 크기의 1차원 벡터를 만든다.

In [39]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


현재는 차원이 1개인 1차원 벡터다. 여기에 첫번째 차원에 1인 차원을 추가해본다. 인덱스가 0부터 시작하므로 0을 인자로 넣으면 첫번째 차원에 1인 차원이 추가된다.

In [40]:
print(ft.unsqueeze(0)) # 인덱스 0 → 첫번째 차원을 의미
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


(3,) 크기의 벡터가 (1, 3) 크기의 2차원 텐서로 변경되었다. 이 연산은 앞서 배운 view로도 구현 가능하다. 2차원으로 바꾸되 첫번째 차원이 1이기를 원한다면 view에 (1, -1)을 인자로 주면 된다.

In [41]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


unsqueeze와 view가 동일한 결과를 만든 것을 확인할 수 있다. 이번엔 인자로 1을 넣어 두번째 차원에 1을 추가해본다. 현재 크기가 (3,)이므로 (3, 1)이 된다.

In [42]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


이번엔 인자로 -1(마지막 차원)을 넣어본다. 현재 크기가 (3,)이므로 마지막 차원에 1을 추가하면 (3, 1)이 되어, 1을 넣은 경우와 결과가 동일하다.

In [43]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


정리하면, **view(), squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절한다.**

###### 타입 캐스팅(Type Casting)

텐서에는 자료형(dtype)이 있다. 예를 들어 32비트 부동소수점은 `torch.FloatTensor`, 64비트 부호 있는 정수는 `torch.LongTensor`를 사용한다. GPU 연산을 위한 자료형(`torch.cuda.FloatTensor` 등)도 있다. 그리고 이 자료형을 변환하는 것을 **타입 캐스팅**이라고 한다.

| Data type | dtype | CPU tensor | GPU tensor |
|---|---|---|---|
| 32-bit float | torch.float32 / torch.float | torch.FloatTensor | torch.cuda.FloatTensor |
| 64-bit float | torch.float64 / torch.double | torch.DoubleTensor | torch.cuda.DoubleTensor |
| 16-bit float | torch.float16 / torch.half | torch.HalfTensor | torch.cuda.HalfTensor |
| 8-bit int (unsigned) | torch.uint8 | torch.ByteTensor | torch.cuda.ByteTensor |
| 8-bit int (signed) | torch.int8 | torch.CharTensor | torch.cuda.CharTensor |
| 16-bit int (signed) | torch.int16 / torch.short | torch.ShortTensor | torch.cuda.ShortTensor |
| 32-bit int (signed) | torch.int32 / torch.int | torch.IntTensor | torch.cuda.IntTensor |
| 64-bit int (signed) | torch.int64 / torch.long | torch.LongTensor | torch.cuda.LongTensor |

우선 실습을 위해 long 타입의 lt라는 텐서를 선언한다.

In [44]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


텐서에 `.float()`를 붙이면 바로 float형으로 타입이 변경된다.

In [45]:
print(lt.float())

tensor([1., 2., 3., 4.])


이번엔 Byte 타입의 bt라는 텐서를 만들어본다.

In [46]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


`.long()`을 붙이면 long 타입, `.float()`를 붙이면 float 타입의 텐서로 변경된다.

In [47]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


###### 연결하기(concatenate)

두 텐서를 연결하는 방법이다. `torch.cat([ ])`를 사용하며, 어느 차원을 늘릴 것인지 dim 인자로 지정할 수 있다. 우선 (2 × 2) 크기의 텐서를 두 개 만든다.

In [48]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [49]:
print(torch.cat([x, y], dim=0)) # dim=0 → 첫번째 차원을 늘린다

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


dim=0으로 연결하니 두 개의 (2 × 2) 텐서가 (4 × 2) 텐서가 되었다. 이번엔 dim=1을 인자로 준다.

In [50]:
print(torch.cat([x, y], dim=1)) # dim=1 → 두번째 차원을 늘린다

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


dim=1로 연결하니 (2 × 4) 텐서가 되었다. 딥 러닝에서는 모델의 입력이나 중간 연산에서 두 텐서를 연결하는 경우가 많은데, 이는 두 가지 정보를 모두 사용한다는 의미를 가진다.

###### 스택킹(Stacking)

연결(concatenate)의 또 다른 방법으로 스택킹(Stacking)이 있다. 스택킹은 영어로 '쌓는다'는 의미다. 때로는 cat보다 스택킹이 편리한데, 스택킹이 많은 연산을 하나로 축약하고 있기 때문이다. 실습을 위해 크기가 (2,)로 모두 동일한 3개의 벡터를 만든다.

In [51]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [52]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


크기가 (2,)인 3개의 벡터가 순차적으로 쌓여 (3 × 2) 텐서가 되었다. 사실 위 작업은 아래 코드와 동일하다.

In [53]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


x, y, z는 원래 (2,) 크기였는데, `.unsqueeze(0)`을 하면서 각각 (1, 2) 크기의 2차원 텐서로 변경되고, 여기에 cat을 적용하면 (3 × 2) 텐서가 된다. torch.stack 한 줄로 끝나는 작업을 cat으로 구현하면 이렇게 복잡해진다. 스택킹에도 dim 인자를 줄 수 있다. dim=1을 주면 두번째 차원이 증가하도록 쌓는다.

In [54]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


두번째 차원이 증가하도록 쌓여 결과적으로 (2 × 3) 텐서가 되었다.

###### ones_like와 zeros_like - 1 또는 0으로 채워진 텐서

입력 텐서와 동일한 크기(shape)이면서 값을 1 또는 0으로 채운 텐서를 생성한다. 실습을 위해 (2 × 3) 텐서를 만든다.

In [55]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


위 텐서에 ones_like를 하면 동일한 크기지만 값이 1로만 채워진 텐서를 생성한다.

In [56]:
print(torch.ones_like(x))  # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


위 텐서에 zeros_like를 하면 동일한 크기지만 값이 0으로만 채워진 텐서를 생성한다.

In [57]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])


###### In-place Operation (덮어쓰기 연산)

연산 결과를 새 텐서가 아니라 기존 텐서에 바로 덮어쓰는 연산이다. 연산자 뒤에 `_`(언더스코어)를 붙인다. 실습을 위해 (2 × 2) 텐서를 만들고 x에 저장한다.

In [58]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [59]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x)         # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


첫번째 출력은 곱하기 2가 수행된 결과를, 두번째 출력은 기존 값을 보여준다. 곱하기 2를 했지만 그 결과를 x에 다시 저장하지 않았으므로 기존 x는 변하지 않는다. 그런데 연산 뒤에 `_`를 붙이면 기존 값을 덮어쓴다.

In [60]:
print(x.mul_(2.)) # 곱하기 2를 수행한 결과를 변수 x에 저장하면서 출력
print(x)          # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


이번에는 x의 값 자체가 덮어쓰기 되어 곱하기 2가 반영된 결과가 출력된다.

## 정리

> 데이터사이언스 분야 한정으로 **3차원 이상의 텐서는 그냥 다차원 행렬 또는 배열**로 간주할 수 있다. 또한 주로 3차원 이상을 텐서라고 하지만, 1차원 벡터나 2차원 행렬도 텐서라고 표현하기도 한다. (벡터 = 1차원 텐서, 행렬 = 2차원 텐서, 그리고 3차원 텐서, 4차원 텐서 ...)

> **batch size** : 훈련 데이터의 개수가 매우 많을 때, 컴퓨터가 한 번에 들고 가서 처리하는 양을 배치 크기라고 한다. 예를 들어 훈련 데이터 하나의 차원이 256이고 데이터가 3,000개라면 전체 크기는 3,000 × 256(2D 텐서)이고, 64개씩 꺼내 처리한다면 한 번에 처리하는 2D 텐서의 크기는 (batch size × dim) = 64 × 256이 된다.

> **shape 표기** : 텐서의 크기를 표현할 때는 ,(콤마)를 쓰기도 하고 ×(곱하기)를 쓰기도 한다. 예) 2행 3열 → (2, 3) 또는 (2 × 3). 그리고 (5, )의 형식은 (1 × 5)를 의미한다.

# 3. 파이썬 클래스(class)

대부분의 파이토치 구현체를 보면 기본적으로 **클래스(Class)** 라는 개념을 적극적으로 사용한다. 이번 챕터에서는 점프투파이썬의 클래스 챕터를 인용한다.

## 함수(function)와 클래스(Class)의 차이

함수와 클래스의 차이를 이해하기 위해, **덧셈을 지속적으로 수행할 수 있는 도구**를 함수와 클래스로 각각 만들어본다.

### 1. 함수(function)로 덧셈기 구현하기

전역 변수 result를 선언하고, add 함수에서 기존 result에 인자로 받은 숫자를 더해 리턴한다. 함수를 두 번 실행하는데 처음엔 3, 두번째엔 4를 넣는다.

In [61]:
result = 0

def add(num):
    global result
    result += num
    return result

print(add(3))
print(add(4))

3
7


처음에는 result가 0이었다가 3이 더해지면서 3이 출력되고, 이어서 4를 입력하면 result의 값이 이미 앞서 3으로 갱신되었기 때문에 3 + 4의 결과로 7이 리턴된다.

### 2. 함수(function)로 두 개의 덧셈기 구현하기

이번엔 **독립적인 두 개의 덧셈기**를 만들고 싶다. 비유하자면 책상에 계산기 두 개를 두고, 첫번째 계산기로는 3+7을, 두번째 계산기로는 3+10을 하는 것이다. 두 계산기는 서로 독립적이어야 한다. 함수로 구현하려면 하나의 함수가 곧 하나의 덧셈기이므로, 두 개의 함수를 독립적으로 만들어야 한다.

In [62]:
result1 = 0
result2 = 0

def add1(num):
    global result1
    result1 += num
    return result1

def add2(num):
    global result2
    result2 += num
    return result2

print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7))

3
7
3
10


두 덧셈기가 서로의 값에 영향을 주지 않고 독립적으로 연산되는 것을 볼 수 있다. 그렇다면 이런 두 개의 덧셈기를 클래스로 만들면 어떻게 될까?

### 3. 클래스(class)로 덧셈기 구현하기

클래스는 마치 **붕어빵 틀**과 같아서, 클래스를 생성한 뒤에는 이걸로 '객체'라는 것을 만들 수 있다. cal1이라는 객체를 만드는 것은 붕어빵 틀로 붕어빵 하나를 찍어내는 것에 비유된다.

In [63]:
class Calculator:
    def __init__(self):   # 객체 생성 시 호출되는 초기화 함수. 이를 생성자라고 한다.
        self.result = 0

    def add(self, num):   # 객체 생성 후 사용할 수 있는 함수.
        self.result += num
        return self.result

객체는 `객체이름 = 클래스이름()` 형태로 생성한다. 클래스가 붕어빵 틀과 같다는 것은, 하나의 클래스를 만든 후에는 여러 개의 객체를 만들 수 있기 때문이다. cal1, cal2 두 개의 객체를 생성하고, 두 객체에 대해 동시에 독립적인 덧셈 연산을 해본다.

In [64]:
cal1 = Calculator()
cal2 = Calculator()

print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10


두 객체가 독립적으로 연산되는 것을 알 수 있다. 앞에서는 독립적인 덧셈기 두 개를 함수로 구현하려고 했을 때 함수를 두 개 만들어야 했지만, 클래스라는 것을 하나 선언하고 이 클래스를 통해 별도의 객체를 생성하자 코드가 훨씬 간결해졌다.